spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_company
    username: root
    password:

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop